### ISSUE TITLE
Introduce ItemDetailView

### ISSUE THREAD

**Issue by wateret** [wateret/mengde#100]
There is no such view for showing item(equipment and consumable) details, so it would be nice to introduce one.

**Comment by wateret** [comment]
CC @sjsinju 

Before doing #10, probably doing this first may help getting used to the code structure.

**Comment by sjsinju** [comment]
I got it. I can take it first. :)

**Comment by sjsinju** [comment]
TODO : I can make ItemDetailView to show as kind of tooltip when mouse is over. (Although tooltip container(#10) is not implemented still)

**Comment by wateret** [comment]
@sjsinju Yes, you may close this and create a new issue for that. Since #10 does not excatly describe what we want to do. (Probably I will close #10 as well.)

**Comment by wateret** [comment]
Oops, only I can close this :)
