### ISSUE TITLE
clang-format usage

### ISSUE THREAD

**Issue by seanshpark** [wateret/mengde#32]
I've tried to run `ci/clang-format.sh` file and got continous errors of
```
$ ci/clang-format.sh
YAML:36:23: error: unknown key 'SplitEmptyFunction'
  SplitEmptyFunction: true
```
Anyone how to run format check in bash shell?

**Comment by wateret** [comment]
@seanshpark Seems like `SplitEmptyFunction` is supported from clang-format 5.

**Comment by wateret** [comment]
Maybe we should check clang-format version from `clang-format.sh`.

**Comment by llFreetimell** [comment]
To support all of arguments in .clang-format file, the version should be higher than 5.
Version 6.0 is available for supporting all of them, I modified script to install 6.0 version(#80)

After installing 6.0 version, I executed and format check runs well though the result was fail.

**Comment by llFreetimell** [comment]
I couldn't modify the script of OS X because I don't know whether OS X install higher version of clang-format automatically or not.
If OS X do not install higher version automatically, we should modify install_deps_osx.sh too.

**Comment by llFreetimell** [comment]
I think we can close this issue, referencing for #80.

**Comment by seanshpark** [comment]
Thanks!
