### ISSUE TITLE
Fix ifdef guard convention

### ISSUE THREAD

**Issue by wateret** [wateret/mengde#43]
Our `#ifdef` guard convention is `#define {NAMESPACE_}{FILENAME}_H_` but most files are just `#define {FILENAME}_H_`.

For example `#ifdef SCENARIO_H_` should be `#ifdef MENGDE_CORE_SCENARIO_H_`.

**Comment by wateret** [comment]
I cannot assign you cause only collaborators can be assigned for personal projects. Anyway you can work on this.

**Comment by sjsinju** [comment]
- [ ] core
- [ ] gui
- [ ] lua
- [ ] util

**Comment by wateret** [comment]
Resolved by #46, thanks! @sjsinju
