### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by wateret** [wateret/mengde#8]
Let's add unit tests for each modules.

- [x] Introduce test framework (Decision : gtest/catch/boost.test)
- [x] Lua binding
- [x] Core module - #4 must be preceded
- [x] Util module

**Comment by wateret** [comment]
#21 should be preceded for this.

**Comment by seanshpark** [comment]
Can we use gtest or build using just a simple c++ program that starts with main() maybe with CTest of CMake
- https://github.com/google/googletest
- https://cmake.org/Wiki/CMake/Testing_With_CTest

**Comment by ragmani** [comment]
We can automatically add tests with CTest of CMake by scanning source code for Google Test. (https://cmake.org/cmake/help/v3.9/module/GoogleTest.html)
If we plan to use gtest in this project, I will look for ways to use it aggressively, because I'm interested in gtest these days.

**Comment by wateret** [comment]
I am good with googletest and CTest. :)

**Comment by wateret** [comment]
Maybe this is more portable. https://github.com/catchorg/Catch2
We should consider this as well.

**Comment by wateret** [comment]
I will close this issue as soon as it gets at least one test for each Lua/Core/Util module.

**Comment by wateret** [comment]
Now that we have at least one test case for each module, closing. Of course we definately need more test cases.
