### ISSUE TITLE
Description about sce folder directory in docs might be wrong.

### ISSUE THREAD

**Issue by llFreetimell** [wateret/mengde#81]
In `mengde/docs/How-to-Run-Example-Scenario.md`, description says `sce` folder should be in `game` folder.
(https://github.com/wateret/mengde/blob/master/docs/How-to-Run-Example-Scenario.md#L10)
After I failed to do so, I tried to copy `sce` folder to `mengde` folder and successed.
Am I wrong or correct?

**Comment by wateret** [comment]
@llFreetimell That could be a path issue. Could you please try run in the folder that contains `game` binary? Then try run `./game`.

**Comment by llFreetimell** [comment]
I mean `play.py` works when `sce` is added to `build/(target-os)/mengde`.
However, what you mentioned works well, I will close this issue.
