### ISSUE TITLE
Moving to C++14

### ISSUE THREAD

**Issue by wateret** [wateret/mengde#82]
I would like to move to C++14, unless there is good reason for not doing this. We're currently on C++11.

### Required compiler versions for C++14

- GCC 5.0 or higher
- Clang 3.4 or higher

### Portability

- [x] Ubuntu 14.04 : AFAIR default C++ compiler is gcc 4.x
- [x] Ubuntu 16.04 or higher : OK
- [x] Raspberry Pi 2 Ubuntu ??.??
- [x] Other OS (far far far... future)
    - [x] Android : AFAIR NDK toolchain is Clang 4 or higher
    - [x] iOS : Not checked yet, but probably no problem

**Comment by seanshpark** [comment]
Sorry for late response. I'll check today :)

**Comment by wateret** [comment]
#85 landed!
