### ISSUE TITLE
[Bug] Can't choose scenario while running with play.py

### ISSUE THREAD

**Issue by sjsinju** [wateret/mengde#98]
I've copied example image source files likes https://github.com/wateret/mengde/blob/master/docs/How-to-Run-Example-Scenario.md. But I couldn't choose scenario in main view.

I figured out it is occurred if it runs with `play.py` (it's ok to run with just `game`.)
@wateret told me it may find wrong path now.

**Comment by wateret** [comment]
@sjsinju Could you please check if you have `sce/example` directory for both of these?

1. `PROJECT_DIR/build/Darwin.x86_64.Debug/mengde/` (default installation dir)
2. `PROJECT_DIR/build/Darwin.x86_64.Debug/game/` (default build dir)

`play.py` executes (1) which is default installation dir. So if you want to use `play.py` for play, make sure the scenario files are present in (1).

**Comment by sjsinju** [comment]
@wateret I am late to reply. It works well after I've copied scenario files to (1) as what you said. Thank you :)
